variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  UNIQUE_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  DEFAULT_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - deploy

Build and push Docker image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  environment: $CI_COMMIT_BRANCH
  variables:
    GIT_DEPTH: "1"
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_TAG --destination $UNIQUE_IMAGE_TAG --destination $DEFAULT_IMAGE_TAG --cache=true

Restart Kubernetes deployment:
  stage: deploy
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  environment: $CI_COMMIT_BRANCH
  script:
    - kubectl config set-cluster k8s --server="${SERVER}" --certificate-authority=${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context competitions --cluster=k8s --user=gitlab --namespace=competitions
    - kubectl config use-context competitions
    - kubectl rollout restart deployment $K8S_DEPLOYMENT_NAME
